Chat test
dzmitryhanets/integrivideo pull request #1
Opened 2019-08-05 07:27 UTC by dzmitryhanets

integrivideo messenger tests

2019-08-05 13:37 UTC, dzmitryrak commented on pom.xml
> +            <artifactId>selenium-chrome-driver</artifactId>
chromedriver Не нужен в зависимостях

2019-08-05 13:37 UTC, dzmitryrak commented on src/test/java/Settings.java
> +    public void settingsModalIsDisplayedTest() {
этот тест не имеет смысла. Ты уже проверил что модалка отображается вводя имя, имейл и аватар

2019-08-05 13:37 UTC, dzmitryrak commented on src/test/java/SiteTest.java
> +    public void siteShouldBeReachedTest() {
этот тест не имеет смысла

2019-08-05 13:38 UTC, dzmitryrak commented on src/test/java/Name.java
> +        Thread.sleep(1000);
Thread.sleep быть нигде не должно. Либо дождись что что-то появится, либо что исчезнет

2019-08-05 15:51 UTC, dzmitryrak commented on src/test/java/Name.java
> +        Thread.sleep(1000);
ну либо implicitWait

2019-08-07 09:59 UTC, dzmitryrak requested changes

2019-08-07 09:59 UTC, dzmitryrak commented on src/test/java/TestsExecutor.java
> +        driver.quit();
чет форматирование скобок кривое

2019-08-07 09:59 UTC, dzmitryrak commented on src/test/java/TestsExecutor.java
> +    public void messageIsDeleted() {
Не описаны другие 2 PageObjects, нет тестов для работы с Settings и Drag & Drop

2019-08-07 09:59 UTC, dzmitryrak commented on src/test/java/Settings.java
> +        element.click();
Весь код в "староем стиле" без PageObjects удалить

2019-08-10 20:50 UTC, dzmitryhanets commented on pom.xml
> +            <artifactId>selenium-chrome-driver</artifactId>
без этой зависимости idea не принимает  driver = new ChromeDriver();

2019-08-12 13:19 UTC, dzmitryrak commented on src/test/java/pages/IntegriVideoChatPage.java
> +            if (i == 11){
ой ой. Это то зачем? Может просто сделать условие не <=, а <
ну и в целом подход неверный

2019-08-12 13:19 UTC, merged